[package]
name = "scope"
version = "0.1.0"
authors = ["Noah Ryan <noah.m.ryan@nasa.gov>"]
edition = "2018"

[dependencies]
num = "0.2"
bitstream-io = "0.8"
myopic = "0.1.2"

[dev-dependencies]
criterion = "0.2"
rand = "0.6"

[[bench]]
name = "bench"
harness = false
